#syntax=docker/dockerfile:1t
FROM docker.io/library/dev-1
COPY cryptorunner-1.py /root/cryptorunner-1.py
COPY results /root/results
COPY apk_downloads /root/apk_downloads
CMD python3 /root/cryptorunner-1.py
